export const RICH_CLOSED_START_INVALID_INPUT =
  'RICH_CLOSED_START_INVALID_INPUT';
export const RICH_CLOSED_SUBMIT_INVALID_INPUT =
  'RICH_CLOSED_SUBMIT_INVALID_INPUT';
export const RICH_CLOSED_SESSION_NOT_FOUND = 'RICH_CLOSED_SESSION_NOT_FOUND';
export const RICH_CLOSED_SESSION_FORBIDDEN = 'RICH_CLOSED_SESSION_FORBIDDEN';
export const RICH_CLOSED_SESSION_ALREADY_COMPLETED =
  'RICH_CLOSED_SESSION_ALREADY_COMPLETED';
export const RICH_CLOSED_SESSION_NOT_COMPLETED =
  'RICH_CLOSED_SESSION_NOT_COMPLETED';
export const RICH_CLOSED_SOURCE_CONTEXT_EMPTY =
  'RICH_CLOSED_SOURCE_CONTEXT_EMPTY';
export const RICH_CLOSED_GENERATION_FAILED = 'RICH_CLOSED_GENERATION_FAILED';
export const RICH_CLOSED_GENERATION_SCHEMA_INVALID =
  'RICH_CLOSED_GENERATION_SCHEMA_INVALID';
export const RICH_CLOSED_GENERATION_CONTRACT_INVALID =
  'RICH_CLOSED_GENERATION_CONTRACT_INVALID';
export const RICH_CLOSED_GENERATION_QUALITY_REJECTED =
  'RICH_CLOSED_GENERATION_QUALITY_REJECTED';
export const RICH_CLOSED_GENERATION_SOURCE_INVALID =
  'RICH_CLOSED_GENERATION_SOURCE_INVALID';
